name: "Jfrog Frogbot OIDC Test"
on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: jfrog/frogbot@v2.29.2
        with:
          oidc-provider-name: github-oidc
        env:
          oidc-provider-name: github-oidc
          JF_PROJECT: ssc-fsdh
          JF_CLI_LOG_LEVEL: "DEBUG"
          JF_URL: https://artifacts-artefacts.devops.cloud-nuage.canada.ca/
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: "main"
